name: AllMusic
main: coloryr.allmusic.AllMusicBukkit
author: Color_yr & DripDrop
version: 3.0.0
loadbefore: [PlaceholderAPI, Vault, Essentials, CMI]

commands:
  music:
    description: AllMusic for DripDrop
    usage: ยง4[AllMusic]ยง6/music help
