name: AllMusic
main: coloryr.allmusic.AllMusicBukkit
author: Color_yr & DripDrop
version: 2.15.4
loadbefore: [PlaceholderAPI, Vault, Essentials, CMI]

commands:
  music:
    description: AllMusic
    usage: ยง4[AllMusic]ยง6/music help
